---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-3
  namespace: servicex-testing-3
spec:
  releaseName: servicex-release-testing-3
  serviceAccountName: servicex-testing-3
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.2.0"
  interval: 5m
  values:
    objectStore:
      enabled: true
      internal: false
      publicURL: s3.ssl-hep.org
      useTLS: true
      useClientTLS: true

    app:
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-testing-3.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      nodeselector:
        storage: rook

    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        tag: develop
        pullPolicy: Always

      CERNOpenData:
        enabled: true
        # image: sslhep/servicex-did-finder-cernopendata

    codeGen:
      uproot:
        enabled: true
        image: sslhep/servicex_code_gen_func_adl_uproot
        tag: v1.1.5-rc.2
        defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer
        defaultScienceContainerTag: uproot4

      python:
        enabled: true
        image: sslhep/servicex_code_gen_python
        tag: develop
        defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer
        defaultScienceContainerTag: uproot4

      atlasr21:
        enabled: true
        image: sslhep/servicex_code_gen_atlas_xaod
        tag: v1.1.5-rc.2
        defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
        defaultScienceContainerTag: 21.2.231

      atlasr22:
        enabled: true
        image: sslhep/servicex_code_gen_atlas_xaod
        tag: v1.1.5-rc.2
        defaultScienceContainerImage: sslhep/servicex_func_adl_xaod_transformer
        defaultScienceContainerTag: 22.2.107

      cmssw-5-3-32:
        enabled: true
        image: sslhep/servicex_code_gen_cms_aod
        tag: v1.1.5-rc.2
        defaultScienceContainerImage: sslhep/servicex_func_adl_cms_aod_transformer
        defaultScienceContainerTag: cmssw-5-3-32

    transformer:
      cachePrefix: '"root://192.170.240.18:1094//"'
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit:
        1

        # Settings for the uproot transformer science container
      language: python
      exec: /generated/transform_single_file.py

    postgres:
      enabled: true

    postgresql:
      primary:
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      existingSecret: servicex-secrets

      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    minio:
      auth:
        existingSecret: servicex-secrets

    minioCleanup:
      enabled: true
      schedule: "0 */8 * * *"
      maxAge: 30
      maxSize: "500G"
      normSize: "400G"

    gridAccount: ivukotic

    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets

    logging:
      logstash:
        logs: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/2612d340-f34e-11ed-a6d8-9f6a16cd6d78?embed=true&_g=()&show-time-filter=true&hide-filter-bar=true"
