---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-3
  namespace: servicex-testing-3
spec:
  releaseName: servicex-release-testing-3
  serviceAccountName: servicex-testing-3
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.1.5-rc.1"
  interval: 5m
  values:

    objectStore:
      enabled: true
      internal: false
      publicURL: s3.ssl-hep.org
      useTLS: true
      useClientTLS: true

    # Settings for the Flask App
    app:
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      tag: develop
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-testing-3.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      nodeselector:
        storage: rook

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        tag: develop
        pullPolicy: Always

      CERNOpenData:
        enabled: true
        image: sslhep/servicex-did-finder-cernopendata
        pullPolicy: Always
    
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always
      defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer
      defaultScienceContainerTag: v1.1.4   

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
    
      cachePrefix: "\"root://192.170.240.18:1094//\""
      
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1

       # Settings for the uproot transformer science container
      language: python
      exec: /generated/transform_single_file.py       

    # enable postgresql backend for servicex
    postgres:
      enabled: true

    postgresql:
      primary:
        resources:
          requests:
            cpu: 4
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      existingSecret: servicex-secrets

      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets

    # Values for the Minio cleanup
    # run once every 8 hours and prune storage to 1T if more than 1.5T is being
    # used files more than 30 days old get removed
    minioCleanup:
      enabled: true
      schedule: "0 */8 * * *"
      maxAge: 30
      maxSize: "1500G"
      normSize: "1T"
          

    gridAccount: xcache
    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets
