---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-int-uproot
  namespace: servicex-int-uproot
spec:
  interval: 60m
  serviceAccountName: servicex-int-uproot
  chart:
    spec:
      chart: servicex
      version: "1.0.29"
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-int-uproot
      interval: 60m
