---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-int-uproot
  namespace: servicex-int-uproot
spec:
  releaseName: servicex-release-int-uproot
  serviceAccountName: servicex-int-uproot
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo   
      version: '1.0.22'
  interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      publicURL: int-uproot-minio.servicex.ssl-hep.org


    # Settings for the Flask App
    app:
      image: sslhep/servicex_app@sha256
      tag: 5f5c284185597740ba5a13af8a6a476842f1dd5dd229bb8c8200cd2cd5386620
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file 
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-int-uproot.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod
      
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you 
    # change the rabbitmq password, otherwise the prior password will 
    # remain in effect and cause problems due to new pods trying to use
    # a different password
    rabbitmq:
      nodeselector: 
        storage: rook
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: '9419'
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: false
        pullPolicy: Always
        image: sslhep/servicex-did-finder@sha256
        tag: edcabc8ad169c3bd85df3205cd7eb664bc99e87a1761b7a70483b00e8eec7f6e

      CERNOpenData:
        enabled: true
        image: sslhep/servicex-did-finder-cernopendata@sha256
        tag: 66ce17a756ebe0861b925f9b556b9cf12de63aa8043017b8a1eb5f1be97ab73d
        pullPolicy: Always


    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot@sha256
      tag: ba5b85148f76acd9f8f595e3f7edf24fbb9723320358d191ccd4b738c61987d3
      pullPolicy: Always


    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer@sha256:2a8183857ed297ebbf93260440d75b663b6eeb328d14db7edb8332fcc6a5d294


    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you 
    # change the postgresql password, otherwise the prior password will 
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      existingSecret: servicex-secrets
      nodeSelector:
        storage: "rook"
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      master:
        nodeSelector:
          kernel-ml: "true"
          storage: "rook"
        

    # Values for Minio Chart
    minio:
      existingSecret: servicex-secrets
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
        - "int-uproot-minio.servicex.ssl-hep.org"
        tls:
        - hosts:
          - int-uproot-minio.servicex.ssl-hep.org
          secretName: uproot-minio-tls


    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: bgalewsk
    rbacEnabled: true

    ## secrets location
    secrets: servicex-secrets
      
