apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-int-uproot
  namespace: servicex-int-uproot
spec:
  releaseName: servicex-release-int-uproot
  serviceAccountName: servicex-int-uproot
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "v1.0.33-rc.8"
  interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: true
      publicURL: int-uproot-minio.servicex.ssl-hep.org
      useTLS: false
      useClientTLS: true
    logging:
      logstash:
        enabled: true
        host: servicex.atlas-ml.org
        port: 5959
        protocol: TCP
        monitor: https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/c2cc1f30-4a5b-11ed-afcf-d91dad577662?embed=true&_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-24h%2Fh%2Cto%3Anow))&show-time-filter=true
        logs:
          https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/bb682100-5558-11ed-afcf-d91dad577662?embed=true&_g=(filters%3A!(('%24state'%3A(store%3AglobalState)%2Cmeta%3A(alias%3A!n%2Cdisabled%3A!f%2Cindex%3A'923eaa00-45b9-11ed-afcf-d91dad577662'%2Ckey%3Ainstance%2Cnegate%3A!f%2Cparams%3A(query%3Aservicex)%2Ctype%3Aphrase)%2Cquery%3A(match_phrase%3A(instance%3A{{
          .Release.Name }}))))%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-24h%2Fh%2Cto%3Anow))&show-query-input=true&show-time-filter=true&hide-filter-bar=true
    app:
      image: sslhep/servicex_app
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      logLevel: INFO
      mailgunDomain: servicex.ssl-hep.org
      slackSigningSecret: dummy
      newSignupWebhook: dummy
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-int-uproot.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod
    rabbitmq:
      nodeselector:
        storage: rook
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      extraConfiguration: |-
        consumer_timeout = 3600000
    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image: memcached
          ttl: 86400
      CERNOpenData:
        enabled: false
        image: sslhep/servicex-did-finder-cernopendata
        pullPolicy: Always
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      defaultTransformerTag: all-newest
    postgres:
      enabled: true
    postgresql:
      primary:
        persistence:
          enabled: false
          storageClass: rook-ceph-block
        nodeSelector:
          kernel-ml: "true"
          storage: rook
      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password
    minio:
      auth:
        existingSecret: servicex-secrets
      tls:
        enabled: false
      service:
        ports:
          api: 9000
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: int-uproot-minio-console.servicex.ssl-hep.org
        tls: true
      apiIngress:
        enabled: true
        tls: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: int-uproot-minio.servicex.ssl-hep.org
    gridAccount: ivukotic
    rbacEnabled: true
    secrets: servicex-secrets
