---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-prod-uproot
  namespace: servicex-prod-uproot
spec:
  releaseName: servicex-release-prod-uproot
  serviceAccountName: servicex-prod-uproot
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.0.28"
  interval: 60m
  values:
    # Default values for servicex.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      publicURL: prod-uproot-minio.servicex.ssl-hep.org

    # Settings for the Flask App
    app:
      image: sslhep/servicex_app
      # tag: develop
      adminEmail: bengal1@illinois.edu
      # pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-prod-uproot.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use

    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      nodeselector:
        storage: rook

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true

    # Settings for the preflight checker - this usually uses the same image as
    # the transformer
    preflight:
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      # pullPolicy: Always

    #
    # Code Generator service
    codeGen:
      enabled: true
      # image: sslhep/servicex_code_gen_func_adl_xaod
      # For uproot deployment
      image: sslhep/servicex_code_gen_func_adl_uproot
      # pullPolicy: Always

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      # pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      # defaultTransformerTag:20220309-1723-stable

    # Values for the Postgresql Chart
    postgres:
      enabled: true
    postgresql:
      existingSecret: servicex-secrets
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      master:
        nodeSelector:
          kernel-ml: "true"

    # Values for Minio Chart
    minio:
      existingSecret: servicex-secrets
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
          - "prod-uproot-minio.servicex.ssl-hep.org"
        tls:
          - hosts:
              - prod-uproot-minio.servicex.ssl-hep.org
            secretName: uproot-minio-tls

    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: bgalewsk
    rbacEnabled: true

    ## secrets location
    secrets: servicex-secrets
