---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-prod-uproot
  namespace: servicex-prod-uproot
spec:
  releaseName: servicex-release-prod-uproot
  serviceAccountName: servicex-prod-uproot
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.1.4"
  interval: 60m
  values:
    # Default values for servicex.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: true
      publicURL: prod-uproot-minio.servicex.ssl-hep.org
      useTLS: false
      useClientTLS: true
    logging:
      logstash:
        enabled: true
        host: servicex.atlas-ml.org
        port: 5959
        protocol: TCP
        
    # Settings for the Flask App
    app:
      # tag: develop
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      logLevel: INFO
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-prod-uproot.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use

    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        # tag: develop
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        # cachePrefix: root://xrd-cache-1.t2.ucsd.edu:7777//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image: memcached
            # tag: alpine
          ttl: 86400
          

      CERNOpenData:
        enabled: false
          # tag: develop
        pullPolicy: Always
            

    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always
      defaultScienceContainerImage: sslhep/servicex_func_adl_uproot_transformer
      defaultScienceContainerTag: v1.1.4


    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      # pullPolicy: Always
      cpuLimit: 1

      # Settings for the uproot transformer science container
      language: python
      exec: /generated/transform_single_file.py

    # Values for the Postgresql Chart
    postgres:
      enabled: true
    postgresql:
      primary:
        persistence:
          enabled: false
          storageClass: rook-ceph-block
        nodeSelector:
          kernel-ml: "true"
          storage: "rook"
      global:
        postgresql: 
          auth: 
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password
      
    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: "prod-uproot-minio.servicex-console.ssl-hep.org"
        tls: true
      apiIngress:
        enabled: true
        tls: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: "prod-uproot-minio.servicex.ssl-hep.org"
        
    minioCleanup:
      enabled: true
    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: ivukotic
    rbacEnabled: true

    ## secrets location
    secrets: servicex-secrets
