---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-testing-1-kustomization
  namespace: servicex-testing-1
resources:
  - servicex-repository.yaml
  - slack-notification.yaml
  - servicex-testing-1-sealed-secret.yaml
  - servicex-testing-1-sealed-slack.yaml
  - grid-certs-sealed.yaml
  - values.yaml
