apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: servicex-slack
  namespace: servicex-testing-1
spec:
  encryptedData:
    address: AgAddilA3E1drkTvcJYJ0hK9XOkh32GbiNA7I9CilK698Gs1Y5vNnmGJ8R+amfcFX8dv7ERDn8a2tD9Pubs1aPkZC/evvomoAzBfOm8y4B/sJ8KX+4CiD9tI95Gkk5soWxtPhLFdzt8Cw9ET6NOX+P1CjA58rqW0C6A3F30azh805i0bXxhUlLZwU0ujGQaFakpvAVImW2Q5VMrQ3Ch4j+kLFEcIS7OBDTVHgjOyNBErqiQaJx/hUl3LkmBIPXxeCBSlAlmiPMvyq6M1ctrklYb1HqyjF+3mIT+zwY74l9cD9SKKNpqvBLhL4mSoKMDAVoopmJ+3Ehpvtb3M5kQWj/ob9YF3ClM77NZo6OS3l//rMju0crbPPQaD2SvsAHzLEBLsV7dB0xHVpK6jXvwIrohR3p5DeUGaM4r0hWoJ11fMuwlS+sfhzuN0cxGFPK8cl3K9KV1e3B1w1Ch7x2G1/DzikgbYjbJI6PDQrDCC19VPqhuQvAYKRPrlL+H3Aek0LCASpAz/AODLgtRNvjkdIuCmkLofn+q6um9bCl1S1gSW8EsLAkVGH62zPnzcinVo7ik7rE0I5XMeSeTFgUSZCLAART+M8JrnwoHcZLaIp9jrnYCpr1iIZ7ODuOh/O+V3bfVhdKIqiWzgNMLoxJcms8g+sYGgHEqQbkQBfvJdWqxfE7eYpZUTbn7/ekyyMm4QQI4q6qCgIbN2RBWGhzaEkaSxwEqV7CVstcuGBHSjE4yuNO+G2eZqcBndgcaRB003z0AwhyBMMTutFr7sriLJhpfTXk8b5foidztfI9pbHRWM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: servicex-slack
      namespace: servicex-testing-1
    type: Opaque

