---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-prod-kustomization
  namespace: servicex-prod
resources:
  - servicex-repository.yaml
  - slack-notification.yaml
  - servicex-secrets-sealed.yaml
  - servicex-slack-sealed.yaml
  - grid-certs-sealed.yaml
  - values.yaml
