---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-2
  namespace: servicex-testing-2
spec:
  interval: 60m
  serviceAccountName: servicex-testing-2
  chart:
    spec:
      chart: servicex
      version: "1.0.22"
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-testing-2
      interval: 60m
