---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-2
  namespace: servicex-testing-2
spec:
  releaseName: servicex-release-testing-2
  serviceAccountName: servicex-testing-2
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.2.0"
  interval: 5m
  values:
    # Default values for servicex.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      publicURL: testing-2-minio.servicex.ssl-hep.org

    # Settings for the Flask App
    app:
      # tag: develop
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-testing-2.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      nodeselector:
        storage: rook

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        # image: sslhep/servicex-did-finder
        # tag: develop
        pullPolicy: Always
        # cachePrefix: root://192.170.240.18:1094//

      CERNOpenData:
        enabled: true
        # image: sslhep/servicex-did-finder-cernopendata
        # tag: develop
        pullPolicy: Always
        cachePrefix:

    #
    # Code Generator service
    codeGen:
      enabled: true
      # image: sslhep/servicex_code_gen_cms_aod
      # For uproot deployment
      image: sslhep/servicex_code_gen_func_adl_uproot
      # tag: pr_cms_fixes
      pullPolicy: Always

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 100
      cpuLimit: 1
      # defaultTransformerImage: sslhep/servicex_func_adl_cms_aod_transformer
      # For uproot deployment
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      # defaultTransformerTag: pr_build_cms_on_the_sly

    # set servicex to use postgresql
    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the postgresql password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      nodeSelector:
        storage: "rook"
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      master:
        nodeSelector:
          kernel-ml: "true"
      existingSecret: servicex-secrets

    # Values for Minio Chart
    minio:
      existingSecret: servicex-secrets
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
          - "testing-2-minio.servicex.ssl-hep.org"
        tls:
          - hosts:
              - testing-2-minio.servicex.ssl-hep.org
            secretName: testing-2-minio-tls

    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: xcache

    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets

    logging:
      logstash:
        logs: "https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/1c14b070-f34e-11ed-a6d8-9f6a16cd6d78?embed=true&_g=()&show-time-filter=true&hide-filter-bar=true"
