---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-prod-xaod-kustomization
  namespace: servicex-prod-xaod

resources:
  - servicex-repository.yaml
  - servicex-release.yaml
  - servicex-prod-xaod-sealed-secret.yaml
  - servicex-prod-xaod-sealed-slack.yaml
  - values.yaml
  - slack-notification.yaml

configurations:
  - kustomizeconfig.yaml
