---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-prod-xaod
  namespace: servicex-prod-xaod
spec:
  interval: 60m
  serviceAccountName: servicex-prod-xaod
  chart:
    spec:
      chart: servicex
      version: '1.0.20'
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-prod-xaod
      interval: 60m
