---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-prod-xaod
  namespace: servicex-prod-xaod
spec:
  releaseName: servicex-release-prod-xaod
  serviceAccountName: servicex-prod-xaod
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.1.4"
  interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: true
      publicURL: prod-xaod-minio.servicex.ssl-hep.org
      useTLS: false
      useClientTLS: true
    logging:
      logstash:
        enabled: true
        host: servicex.atlas-ml.org
        port: 5959
        protocol: TCP

    # Settings for the Flask App
    app:
      # image: sslhep/servicex_app
      # tag: "develop"
      adminEmail: bengal1@illinois.edu
      # pullPolicy: Always
      auth: true
      # replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-prod-xaod.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      nodeselector:
        storage: rook
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets

    # Settings for the DID Finder
    didFinder:
      image: sslhep/servicex-did-finder
        #      image: sslhep/servicex-did-finder-cernopendata
      rucio:
        enabled: true
        # tag: develop
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        # cachePrefix: root://xrd-cache-1.t2.ucsd.edu:7777//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image: memcached
            # tag: alpine
          ttl: 86400  
        image: sslhep/servicex-did-finder
        CERNOpenData:
          enabled: false

    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_atlas_xaod

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      # pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_xaod_transformer
      language: bash
      exec: /generated/transform_single_file.sh       

    # enabled postgresql backend for servicex
    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the postgresql password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      primary:
        persistence:
          enabled: false
          storageClass: rook-ceph-block
        nodeSelector:
          kernel-ml: "true"
          storage: "rook"
      global:
        postgresql: 
          auth: 
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets
      
      tls:
        enabled: false
      service:
        ports:
          api: 9000

      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: "prod-xaod-minio-console.servicex.ssl-hep.org"
        tls: true
      apiIngress:
        enabled: true
        tls: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hostname: "prod-xaod-minio.servicex.ssl-hep.org"
        
    minioCleanup:
      enabled: true          
    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: ivukotic
    rbacEnabled: true

    ## secrets location
    secrets: servicex-secrets
