---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-prod-xaod
  namespace: servicex-prod-xaod
spec:
  releaseName: servicex-release-prod-xaod
  serviceAccountName: servicex-prod-xaod
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "1.0.27"
  interval: 60m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      publicURL: prod-xaod-minio.servicex.ssl-hep.org

    # Settings for the Flask App
    app:
      # image: sslhep/servicex_app
      # tag: "develop"
      adminEmail: bengal1@illinois.edu
      # pullPolicy: Always
      auth: true
      # replicas: 1
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-prod-xaod.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      nodeselector:
        storage: rook
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 30s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets

    # Settings for the DID Finder
    didFinder:
      image: sslhep/servicex-did-finder-cernopendata
      # tag: "v1.0.0-rc.4"
      rucio:
        image: sslhep/servicex-did-finder
        # tag: "v1.0.0-rc.4"
        enabled: true

    #
    # Code Generator service
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_atlas_xaod
      # tag: "v1.0.0-rc.4"
      # For uproot deployment
      # image: sslhep/servicex_code_gen_func_adl_uproot
      # pullPolicy: Always

    # Pull policy for the worker pods - the image and version are specified as
    # part of the transform request
    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      # pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_xaod_transformer:20220311-2056-stable
      # tag: "v1.0.0-rc.4"
      # For uproot deployment
      #  defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer:develop

    # enabled postgresql backend for servicex
    postgres:
      enabled: true

    # Values for the Postgresql Chart
    #
    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the postgresql password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    # the new password and then getting authorization error
    postgresql:
      existingSecret: servicex-secrets
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      master:
        nodeSelector:
          kernel-ml: "true"

    # Values for Minio Chart
    minio:
      existingSecret: servicex-secrets
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
        hosts:
          - "prod-xaod-minio.servicex.ssl-hep.org"
        tls:
          - hosts:
              - prod-xaod-minio.servicex.ssl-hep.org
            secretName: xaod-minio-tls

    ###### Settings for Authenticating with the CERN Infrastructure #######

    gridAccount: bgalewsk
    rbacEnabled: true

    ## secrets location
    secrets: servicex-secrets
