---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-testing-4-kustomization
  namespace: servicex-testing-4
resources:
  - servicex-repository.yaml
  - servicex-testing-4-sealed-secret.yaml
  - servicex-testing-4-sealed-slack.yaml
  - values.yaml
  - slack-notification.yaml
