---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing-4
  namespace: servicex-testing-4
spec:
  releaseName: servicex-release-testing-4
  serviceAccountName: servicex-testing-4
  chart:
    spec:
      chart: servicex
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
      version: "v1.0.34"
  interval: 5m
  values:
    # Enable deployment of Minio Object Store with this chart - use this if you
    # want to have the option of delivering results as parquet files
    objectStore:
      enabled: true
      internal: false
      publicURL: s3.ssl-hep.org
      useTLS: true
      useClientTLS: true

    # Settings for the Flask App

    app:
      adminEmail: bengal1@illinois.edu
      pullPolicy: Always
      auth: true
      replicas: 1
      logLevel: INFO
      mailgunDomain: servicex.ssl-hep.org
      # need dummy values so that it's in the config file
      slackSigningSecret: "dummy"
      newSignupWebhook: "dummy"
      ingress:
        enabled: true
        tls:
          enabled: true
          host: servicex-release-testing-4.servicex.ssl-hep.org
          clusterIssuer: letsencrypt-prod

    # ************************ IMPORTANT NOTE ***********************
    # If you enable persistance, you must delete the pv claim if you
    # change the rabbitmq password, otherwise the prior password will
    # remain in effect and cause problems due to new pods trying to use
    rabbitmq:
      metrics:
        enabled: false
        plugins: rabbitmq_prometheus
        podAnnotations:
          prometheus.io/port: "9419"
          prometheus.io/scrape: "true"
        prometheusRule:
          additionalLabels: {}
          enabled: false
          namespace: ""
          rules: []
        serviceMonitor:
          additionalLabels: {}
          enabled: true
          honorLabels: false
          interval: 40s
      persistence:
        enabled: false
        storageClass: rook-ceph-block
      auth:
        existingErlangSecret: servicex-secrets
        existingPasswordSecret: servicex-secrets
      nodeselector:
        storage: rook

    # Settings for the DID Finder
    didFinder:
      rucio:
        enabled: true
        image: sslhep/servicex-did-finder
        pullPolicy: Always
        cachePrefix: root://192.170.240.18:1094//
        servicex_latitude: 41.78
        servicex_longitude: -87.7
        memcache:
          enabled: true
          image:
            memcached
          ttl: 86400

      CERNOpenData:
        enabled: true
        image: sslhep/servicex-did-finder-cernopendata
        pullPolicy: Always
    
    codeGen:
      enabled: true
      image: sslhep/servicex_code_gen_func_adl_uproot
      pullPolicy: Always

    transformer:
      autoscaler:
        enabled: true
        cpuScaleThreshold: 30
        minReplicas: 10
        maxReplicas: 750
      pullPolicy: Always
      cpuLimit: 1
      defaultTransformerImage: sslhep/servicex_func_adl_uproot_transformer
      
    postgres:
      enabled: true

    postgresql:
      primary:
        resources:
          requests:
            cpu: 8
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      global:
        postgresql:
          auth:
            database: servicex
            existingSecret: servicex-secrets
            secretKeys:
              adminPasswordKey: postgresql-password

    # Values for Minio Chart
    minio:
      auth:
        existingSecret: servicex-secrets

    ###### Settings for Authenticating with the CERN Infrastructure #######
    gridAccount: xcache
    rbacEnabled: true

    ### secrets location
    secrets: servicex-secrets
